import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://class.example/'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,localStorage:dom.window.localStorage});Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.fetch=async()=>new Response(JSON.stringify({rows:[],resetVersion:'0'}));
const React=await import('react');const {render,cleanup,fireEvent,screen}=await import('@testing-library/react');const {default:App}=await import('../src/App.tsx');
const gems=[['협동','책임'],['배려','질서'],['경청','성실'],['공감','끈기'],['존중','경청']];
for(let group=1;group<=5;group++)test(`모둠 ${group}: 고정 조작 배지·뒤로 기록 유지·복원·선택 수정`,()=>{
 const selected=gems[group-1];cleanup();localStorage.clear();render(React.createElement(App));assert.equal(document.querySelector('.operator-badge'),null);assert.equal(screen.queryByRole('button',{name:'← 뒤로'}),null);cleanup();
 for(const [stage,number] of Object.entries({leader:'①',select:'①',confirm:'①',roles:'②',discussion:'②',activity:'③',oneDone:'③',captured:'③',return:'③',photos:'④',upload:'④'})){
 localStorage.clear();localStorage.setItem('diamond-maeum-v1',JSON.stringify({group,selected,done:stage==='oneDone'?[selected[0]]:['captured','return','photos','upload'].includes(stage)?selected:[],screen:stage,extra:null,leaderConfirmed:stage==='leader'}));render(React.createElement(App));assert.equal(document.querySelector('.operator-number')?.textContent,number);if(stage!=='leader')assert.ok(screen.getByRole('button',{name:'← 뒤로'}));assert.equal(document.querySelector('.role-cue'),null);cleanup();
 }
 for(const [from,to] of Object.entries({select:'leader',confirm:'select',roles:'select',discussion:'roles',activity:'discussion',oneDone:'activity',captured:'oneDone',return:'oneDone',photos:'return',upload:'photos'})){
  const done=['captured','return','photos','upload'].includes(from)?selected:from==='oneDone'?[selected[0]]:[];localStorage.clear();localStorage.setItem('diamond-maeum-v1',JSON.stringify({group,selected,done,screen:from,leaderConfirmed:true,role:2,canva:from==='upload',extra:null}));render(React.createElement(App));fireEvent.click(screen.getByRole('button',{name:'← 뒤로'}));let saved=JSON.parse(localStorage.getItem('diamond-maeum-v1')!);assert.equal(saved.screen,to,from+' → '+to);assert.deepEqual(saved.selected,selected);assert.deepEqual(saved.done,done);assert.equal(saved.role,2);assert.equal(saved.canva,false);assert.equal(document.querySelector('.setup'),null);cleanup();render(React.createElement(App));saved=JSON.parse(localStorage.getItem('diamond-maeum-v1')!);assert.equal(saved.screen,to,'새로고침 '+from);assert.deepEqual(saved.done,done);cleanup();
 }
 localStorage.setItem('diamond-maeum-v1',JSON.stringify({group,selected,done:[selected[0]],screen:'oneDone',extra:null}));render(React.createElement(App));const back=()=>fireEvent.click(screen.getByRole('button',{name:'← 뒤로'}));back();assert.equal(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).screen,'activity');back();assert.ok(screen.getByRole('heading',{name:'두 마음보석을 어떻게 표현할지 이야기해요'}));assert.deepEqual(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).done,[selected[0]]);cleanup();render(React.createElement(App));assert.ok(screen.getByRole('heading',{name:'두 마음보석을 어떻게 표현할지 이야기해요'}));back();back();assert.equal(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).screen,'select');assert.deepEqual(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).selected,selected);assert.deepEqual(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).done,[selected[0]]);fireEvent.click(screen.getByRole('button',{name:selected[0],exact:true}));assert.deepEqual(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).done,[]);cleanup();
 localStorage.setItem('diamond-maeum-v1',JSON.stringify({group,selected,done:selected,screen:'upload',canva:true,extra:null}));render(React.createElement(App));back();assert.equal(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).screen,'photos');assert.equal(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).canva,false);assert.deepEqual(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).done,selected);back();assert.equal(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).screen,'return');cleanup();
});
test.afterEach(()=>cleanup());test.after(()=>dom.window.close());
