import test from 'node:test';import assert from 'node:assert/strict';import {handleProgress} from '../server/progress-core.mjs';
class TestStore{data=new Map();async get(k){return this.data.get(k)||null}async setJSON(k,v){this.data.set(k,structuredClone(v))}async delete(k){this.data.delete(k)}async list(){return{blobs:[...this.data.keys()].map(key=>({key}))}}}
const request=(group,device,screen='activity',selected=group===5?['존중','경청']:['협동','책임'],revision=Date.now())=>new Request('https://class.example/api/progress',{method:'POST',body:JSON.stringify({group,device,record:{group,selected,done:['return','photos','upload'].includes(screen)?selected:[],screen,extra:null},revision})});
test('서로 다른 태블릿의 기록이 같은 교사 화면에 나타나고 참관 기록은 분리됨',async()=>{const store=new TestStore();await Promise.all([handleProgress(request(1,'tablet-one'),store),handleProgress(request(5,'teacher-one','roles'),store),handleProgress(request(5,'teacher-two','return'),store)]);const response=await handleProgress(new Request('https://class.example/api/progress'),store);const {rows}=await response.json();assert.equal(rows.length,3);assert.equal(rows.filter(r=>r.category==='child').length,1);assert.equal(rows.filter(r=>r.category==='observer').length,2);assert.ok(rows.some(r=>r.stage==='🪑 모둠 자리로 이동'));});
test('같은 태블릿 업데이트와 기록 초기화가 다른 모둠을 지우지 않음',async()=>{const store=new TestStore();await handleProgress(request(1,'one','activity',undefined,1),store);await handleProgress(request(5,'two','activity',undefined,1),store);await handleProgress(request(1,'one','select',[],2),store);const x=(await(await handleProgress(new Request('https://class.example/api/progress'),store)).json()).rows;assert.equal(x.length,2);assert.deepEqual(JSON.parse(x.find(r=>r.group_id===1).record_json).selected,[]);assert.equal(JSON.parse(x.find(r=>r.group_id===5).record_json).selected.length,2)});
test('잘못된 미덕·기기·모둠 기록은 저장되지 않음',async()=>{const store=new TestStore();assert.equal((await handleProgress(request(1,'one','activity',['존중']),store)).status,400);assert.equal((await handleProgress(request(1,'../one'),store)).status,400);assert.equal((await handleProgress(request(7,'one'),store)).status,400);assert.equal(store.data.size,0)});
test('늦게 도착한 이전 기록은 새 기록을 덮어쓰지 않음',async()=>{const store=new TestStore();await handleProgress(request(1,'one','return',undefined,2),store);await handleProgress(request(1,'one','roles',undefined,1),store);assert.equal([...store.data.values()][0].stage,'🪑 모둠 자리로 이동')});
test('서버 연결 실패를 성공으로 표시하지 않음',async()=>{const store={get(){throw new Error('offline')}};const response=await handleProgress(new Request('https://class.example/api/progress'),store);assert.equal(response.status,503)});

const resetRequest=(version='0')=>new Request('https://class.example/api/progress',{method:'POST',body:JSON.stringify({action:'reset',resetVersion:version})});
test('전체 초기화: 네 모둠·참관 서버 삭제, 이전 오프라인 기록 차단, 새 기록 허용',async()=>{const store=new TestStore();for(const group of [1,2,3,4,5]){const selected=[['협동','책임'],['배려','질서'],['경청','성실'],['공감','끈기'],['존중','경청']][group-1];assert.equal((await handleProgress(request(group,'reset-'+group,'activity',selected),store)).status,200)}const response=await handleProgress(resetRequest(),store);assert.equal(response.status,200);const {resetVersion}=await response.json();assert.notEqual(resetVersion,'0');assert.equal(store.data.size,1);let snapshot=await(await handleProgress(new Request('https://class.example/api/progress'),store)).json();assert.equal(snapshot.rows.length,0);assert.equal(snapshot.resetVersion,resetVersion);assert.equal((await handleProgress(request(1,'old-offline'),store)).status,409);assert.equal((await handleProgress(resetRequest(),store)).status,409);const fresh=new Request('https://class.example/api/progress',{method:'POST',body:JSON.stringify({device:'new-device',group:1,resetVersion,record:{group:1,selected:[],done:[],screen:'leader',leaderConfirmed:true}})});assert.equal((await handleProgress(fresh,store)).status,200);snapshot=await(await handleProgress(new Request('https://class.example/api/progress'),store)).json();assert.equal(snapshot.rows[0].stage,'오늘의 진행자 확인');assert.equal(JSON.parse(snapshot.rows[0].record_json).leaderConfirmed,true)});
test('초기화와 겹쳐 늦게 완료된 POST도 서버 목록에서 부활하지 않음',async()=>{const store=new TestStore();const normal=store.setJSON.bind(store);let hold;let started;const gate=new Promise(r=>hold=r),writing=new Promise(r=>started=r);store.setJSON=async(k,v)=>{if(k==='child/1/racing'){started();await gate}return normal(k,v)};const pending=handleProgress(request(1,'racing'),store);await writing;const reset=await handleProgress(resetRequest(),store);assert.equal(reset.status,200);hold();assert.equal((await pending).status,409);const {rows}=await(await handleProgress(new Request('https://class.example/api/progress'),store)).json();assert.equal(rows.length,0)});
