import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://class.example/'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,localStorage:dom.window.localStorage});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
Object.defineProperty(navigator,'sendBeacon',{value:()=>true,configurable:true});
globalThis.fetch=async()=>new Response(JSON.stringify({ok:true,rows:[]}),{headers:{'Content-Type':'application/json'}});
const React=await import('react');
const {render,cleanup,fireEvent,screen}=await import('@testing-library/react');
const {default:App}=await import('../src/App.tsx');
const cases=[['다람쥐 모둠',['협동','책임'],'빨간색'],['낙엽 모둠',['배려','질서'],'노란색'],['잠자리 모둠',['경청','성실'],'초록색'],['바람 모둠',['공감','끈기'],'파란색'],['참관교사용',['존중','경청'],'보라색']];
const assertOne=()=>{assert.ok(screen.getByRole('heading',{name:/하나 완성/}));assert.ok(screen.getByText('이제 이 마음보석을 표현해요'));const text=document.querySelector('main')!.textContent!;assert.doesNotMatch(text,/모둠 자리로 돌아가요|사진 확인|사진을 함께 확인|Canva|사진 올리기|색 칸/);assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);assert.equal(document.querySelectorAll('.gem[aria-pressed="true"]').length,1);};
for(let i=0;i<cases.length;i++)test(`${cases[i][0]} 실제 화면: 1/2 차단·새로고침·홈 복귀·2/2 이후 순서`,async()=>{
 cleanup();localStorage.clear();const [name,gems,color]=cases[i];const group=i+1;
 localStorage.setItem('diamond-maeum-v1',JSON.stringify({group,selected:[],done:[],screen:'select',extra:null}));
 render(React.createElement(App));
 fireEvent.click(screen.getByRole('button',{name:gems[0] as string,exact:true}));fireEvent.click(screen.getByRole('button',{name:gems[1] as string,exact:true}));fireEvent.click(screen.getByRole('button',{name:/선택했어요/}));fireEvent.click(screen.getByRole('button',{name:/우리 역할 보기/}));
 assert.ok(screen.getByText('친구들의 생각을 들어요.'));for(const role of ['① 진행자','② 감독','③ 촬영자','④ 올림이','⑤ 완성이'])assert.ok(screen.getByRole('button',{name:new RegExp(role+'$')}));for(const [role,icon] of [['③ 촬영자','camera'],['④ 올림이','canva']]){const card=screen.getByRole('button',{name:new RegExp(role+'$')});assert.ok(card.querySelector('.role-picture'));assert.equal(card.querySelector('img')?.getAttribute('src'),'/app-icons/'+icon+'.png');fireEvent.click(card);assert.equal(card.getAttribute('aria-expanded'),'true');}for(const role of ['① 진행자','② 감독','⑤ 완성이']){const card=screen.getByRole('button',{name:new RegExp(role+'$')});assert.ok(card.querySelector('.role-picture'));assert.equal(card.querySelector('img'),null);}fireEvent.click(screen.getByRole('button',{name:/② 감독$/}));assert.ok(screen.getByText('우리 생각이 잘 보이도록 장면을 만들어요.'));fireEvent.click(screen.getByRole('button',{name:/두 마음보석 이야기해요/}));assert.ok(screen.getByRole('heading',{name:'두 마음보석을 어떻게 표현할지 이야기해요'}));assert.equal(screen.getAllByText('어디에서 찍을까?').length,2);assert.equal(screen.getAllByText('어떤 모습으로 표현할까?').length,2);assert.equal(screen.queryByRole('button',{name:/이 마음보석 다 했어요/}),null);assert.equal(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).screen,'discussion');cleanup();render(React.createElement(App));assert.ok(screen.getByRole('heading',{name:'두 마음보석을 어떻게 표현할지 이야기해요'}));fireEvent.click(screen.getByRole('button',{name:/의논했어요! 촬영하러 출발/}));
 assert.equal(screen.getByRole('img',{name:'카메라 앱 아이콘'}).getAttribute('src'),'/app-icons/camera.png');fireEvent.click(screen.getAllByRole('button',{name:/이 마음보석 다 했어요/})[0]);assertOne();
 let saved=JSON.parse(localStorage.getItem('diamond-maeum-v1')!);assert.deepEqual(saved.done,[gems[0]]);assert.equal(saved.screen,'oneDone');
 // 실제 앱을 제거했다 다시 실행하여 새로고침의 저장 복원 경로 검사.
 cleanup();render(React.createElement(App));assertOne();
 fireEvent.click(screen.getByRole('button',{name:'홈'}));
 fireEvent.click(screen.getByRole('button',{name:/처음으로$/}));
 fireEvent.click(screen.getByRole('button',{name:name as string,exact:true}));assertOne();
 fireEvent.click(screen.getByRole('button',{name:/이 마음보석 다 했어요/}));
 assert.ok(screen.getByRole('heading',{name:/두 마음보석을 모두 표현했어요/}));assert.equal(document.querySelectorAll('.gem[aria-pressed="true"]').length,2);
 assert.equal(screen.queryByRole('button',{name:/모였어요/}),null);assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);
 fireEvent.click(screen.getByRole('button',{name:/모둠 자리로 돌아가요/}));
 assert.ok(screen.getByRole('heading',{name:'모둠 자리로 돌아가요'}));assert.equal(screen.getAllByRole('img',{name:'다섯 친구가 모둠 책상 앞 의자에 앉은 그림'}).length,2);
 assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);
 fireEvent.click(screen.getByRole('button',{name:/모였어요/}));assert.ok(screen.getByRole('heading',{name:'우리 사진을 함께 확인해요'}));assert.equal(screen.getByRole('img',{name:'갤러리 앱 아이콘'}).getAttribute('src'),'/app-icons/gallery.png');assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);
 fireEvent.click(screen.getByRole('button',{name:/사진을 확인했어요/}));assert.ok(screen.getByText(new RegExp(color+' 칸에')));
 assert.equal(screen.getByRole('img',{name:'Canva 앱 아이콘'}).getAttribute('src'),'/app-icons/canva.png');assert.equal(document.querySelector('img[src="/canva-logo.svg"]'),null);const link=screen.getByRole('link',{name:/우리 사진 올리기/});assert.equal(link.getAttribute('href'),'https://canva.link/lg44g9coxwzxamt');
 saved=JSON.parse(localStorage.getItem('diamond-maeum-v1')!);assert.deepEqual(saved.done,gems);assert.equal(saved.screen,'upload');
 assert.equal(screen.queryByRole('button',{name:/사진 올렸어요/}),null);assert.doesNotMatch(document.querySelector('main')!.textContent!,/뒤로|돌아와요|완료 화면/);
 link.addEventListener('click',e=>e.preventDefault());fireEvent.click(link);saved=JSON.parse(localStorage.getItem('diamond-maeum-v1')!);assert.equal(saved.canva,true);assert.equal(saved.screen,'upload');cleanup();render(React.createElement(App));assert.ok(screen.getByRole('link',{name:/우리 사진 올리기/}));assert.equal(screen.queryByRole('button',{name:/사진 올렸어요/}),null);assert.equal(JSON.parse(localStorage.getItem('diamond-maeum-v1')!).canva,true);
 cleanup();
});
for(let group=1;group<=5;group++)test(`모둠 ${group}: 진행자 직접 확인·취소·새로고침·다음 버튼`,()=>{cleanup();localStorage.clear();render(React.createElement(App));fireEvent.click(screen.getByRole('button',{name:cases[group-1][0] as string,exact:true}));assert.ok(screen.getByRole('heading',{name:'🌟 오늘의 진행자'}));const card=screen.getByRole('button',{name:'① 진행자'});let next=screen.getByRole('button',{name:/진행자 확인했어요/});assert.equal((next as HTMLButtonElement).disabled,true);assert.equal(card.getAttribute('aria-pressed'),'false');fireEvent.click(card);assert.equal(card.getAttribute('aria-pressed'),'true');assert.equal((next as HTMLButtonElement).disabled,false);fireEvent.click(card);assert.equal((next as HTMLButtonElement).disabled,true);fireEvent.click(card);cleanup();render(React.createElement(App));assert.equal(screen.getByRole('button',{name:'① 진행자'}).getAttribute('aria-pressed'),'true');next=screen.getByRole('button',{name:/진행자 확인했어요/});fireEvent.click(next);assert.ok(screen.getByText('2개를 골라요'));assert.equal(document.querySelectorAll('.gem').length,4);cleanup()});
test.afterEach(()=>cleanup());
test.after(()=>dom.window.close());
