import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://class.example/'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,localStorage:dom.window.localStorage});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
Object.defineProperty(navigator,'sendBeacon',{value:()=>true,configurable:true});
globalThis.fetch=async()=>new Response(JSON.stringify({ok:true,rows:[]}),{headers:{'Content-Type':'application/json'}});
const React=await import('react');
const {render,cleanup,fireEvent,screen}=await import('@testing-library/react');
const {default:App}=await import('../src/App.tsx');
const cases=[['다람쥐 모둠',['협동','책임'],'빨간색'],['낙엽 모둠',['배려','질서'],'노란색'],['잠자리 모둠',['경청','성실'],'초록색'],['바람 모둠',['공감','끈기'],'파란색'],['참관교사용',['존중','경청'],'보라색']];
const assertOne=()=>{assert.ok(screen.getByRole('heading',{name:/하나 완성/}));assert.ok(screen.getByText('이제 이 마음보석을 표현해요'));const text=document.querySelector('main')!.textContent!;assert.doesNotMatch(text,/모둠 자리로 돌아가요|사진 확인|사진을 함께 확인|Canva|사진 올리기|색 칸/);assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);assert.equal(document.querySelectorAll('.gem[aria-pressed="true"]').length,1);};
for(let i=0;i<cases.length;i++)test(`${cases[i][0]} 실제 화면: 1/2 차단·새로고침·홈 복귀·2/2 이후 순서`,async()=>{
 cleanup();localStorage.clear();const [name,gems,color]=cases[i];const group=i+1;
 localStorage.setItem('diamond-maeum-v1',JSON.stringify({group,selected:gems,done:[],screen:'activity',extra:null}));
 render(React.createElement(App));
 fireEvent.click(screen.getAllByRole('button',{name:/이 마음보석 다 했어요/})[0]);assertOne();
 let saved=JSON.parse(localStorage.getItem('diamond-maeum-v1')!);assert.deepEqual(saved.done,[gems[0]]);assert.equal(saved.screen,'oneDone');
 // 실제 앱을 제거했다 다시 실행하여 새로고침의 저장 복원 경로 검사.
 cleanup();render(React.createElement(App));assertOne();
 fireEvent.click(screen.getByRole('button',{name:'홈'}));
 fireEvent.click(screen.getByRole('button',{name:/처음으로$/}));
 fireEvent.click(screen.getByRole('button',{name:name as string,exact:true}));assertOne();
 fireEvent.click(screen.getByRole('button',{name:/이어서 표현해요/}));
 fireEvent.click(screen.getAllByRole('button',{name:/이 마음보석 다 했어요/})[1]);
 assert.ok(screen.getByRole('heading',{name:/두 마음보석을 모두 표현했어요/}));assert.equal(document.querySelectorAll('.gem[aria-pressed="true"]').length,2);
 assert.equal(screen.queryByRole('button',{name:/모였어요/}),null);assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);
 fireEvent.click(screen.getByRole('button',{name:/모둠 자리로 돌아가요/}));
 assert.ok(screen.getByRole('heading',{name:'모둠 자리로 돌아가요'}));assert.equal(screen.getAllByRole('img',{name:'다섯 친구가 모둠 책상 앞 의자에 앉은 그림'}).length,2);
 assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);
 fireEvent.click(screen.getByRole('button',{name:/모였어요/}));assert.ok(screen.getByRole('heading',{name:'우리 사진을 함께 확인해요'}));assert.equal(document.querySelectorAll('a[href*="canva"]').length,0);
 fireEvent.click(screen.getByRole('button',{name:/사진을 확인했어요/}));assert.ok(screen.getByText(new RegExp(color+' 칸에')));
 const link=screen.getByRole('link',{name:/우리 사진 올리기/});assert.equal(link.getAttribute('href'),'https://canva.link/lg44g9coxwzxamt');
 saved=JSON.parse(localStorage.getItem('diamond-maeum-v1')!);assert.deepEqual(saved.done,gems);assert.equal(saved.screen,'upload');
 cleanup();
});
test.afterEach(()=>cleanup());
test.after(()=>dom.window.close());
