'use client';
import {normalizeFlow,toggleDone,moveTo,stageOf} from '../server/activity-flow.mjs';
import {useEffect,useRef,useState, type CSSProperties} from 'react';
const groups=[['협동','책임','경청','감사'],['배려','질서','공감','용기'],['경청','성실','협동','예의'],['공감','끈기','배려','자주'],['존중','경청','공감','협동']];
const gemColors:Record<string,[string,string]>={존중:['#35b8ad','#165b62'],협동:['#7961d2','#38277f'],책임:['#a3a3aa','#454650'],경청:['#62bfdf','#14566d'],감사:['#ef555b','#932a30'],배려:['#c97872','#703b39'],질서:['#d263a7','#7a285c'],공감:['#d5a64d','#795722'],용기:['#61c894','#226849'],성실:['#b3d663','#5b7425'],예의:['#e5985e','#86452b'],끈기:['#646dd0','#292f7d'],자주:['#dfc351','#7a661b']};
const groupNames=['다람쥐','낙엽','잠자리','바람','참관교사용'];
const symbol=(n:number)=> n===5?<span className="teacher-art" aria-hidden="true">👩🏻‍🏫</span>:<span className={'group-art art'+n} aria-hidden="true"/>;
const hearts=['❤️','💛','💚','💙','🟣'];
const roles=[['💬','진행자','친구들의 생각을 들어요.'],['🎬','감독','우리 생각이 잘 보이도록 장면을 만들어요.'],['📷','촬영자','사진을 찍어요.'],['📤','올림이','사진을 캔바에 올려요.'],['💎','완성이','우리 사진을 미덕송에 넣어요.']];
const pictureLabels=['친구들이 함께 이야기하는 그림','친구들이 보석을 함께 고르는 그림','태블릿으로 친구들을 촬영하는 그림','두 손을 들고 완료를 표시하는 유아 그림','다섯 친구가 모둠 책상 앞 의자에 앉은 그림','다섯 친구가 태블릿 사진을 함께 확인하는 그림','친구들이 함께 촬영 장면을 만드는 그림','사진을 올리는 그림','사진을 미덕송 화면에 넣는 그림'];
const picture=(n:number,cls='')=><span className={'action-picture picture'+n+' '+cls} role="img" aria-label={pictureLabels[n-1]}/>;
const rolePictures=[1,7,3,8,9];
const canvaLink='https://canva.link/lg44g9coxwzxamt';
type RecordState={group:number;selected:string[];done:string[];screen:string;extra:string|null;pending?:string|null;role?:number;canva?:boolean;uploaded?:boolean};
const empty=(group=0):RecordState=>({group,selected:[],done:[],screen:'select',extra:null});
const key='diamond-maeum-v1';
const colors=['#e4424c','#e8bc23','#2fa56b','#3889db','#975aca'];
const colorNames=['빨간색','노란색','초록색','파란색','보라색'];
const label=(g:number)=>g===5?'참관교사용':groupNames[g-1]+' 모둠';
const stage=stageOf;
export default function Home(){
 const [s,setS]=useState<RecordState>(empty()),[ready,setReady]=useState(false),[settings,setSettings]=useState(false),[reset,setReset]=useState(false),[change,setChange]=useState(false),[role,setRole]=useState(-1),[notice,setNotice]=useState(''),[storageIssue,setStorageIssue]=useState(false);const [homeConfirm,setHomeConfirm]=useState(false),[dashboard,setDashboard]=useState(false),[rows,setRows]=useState<any[]>([]),[syncError,setSyncError]=useState(false);const records=useRef<Record<number,RecordState>>({});const device=useRef('');const latestPayload=useRef<any>(null);const writeQueue=useRef(Promise.resolve());const hold=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{try{device.current=localStorage.getItem('maeum-device')||(typeof crypto.randomUUID==='function'?crypto.randomUUID():'tablet-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));localStorage.setItem('maeum-device',device.current);records.current=JSON.parse(localStorage.getItem('maeum-group-records')||'{}');const raw=localStorage.getItem(key);if(raw){const x=JSON.parse(raw);if(Number.isInteger(x.group)&&x.group>=1&&x.group<=5&&Array.isArray(x.selected)&&Array.isArray(x.done)){const selected=[...new Set<string>(x.selected.filter((v:string)=>groups[x.group-1].includes(v)))];const r=normalizeFlow({...empty(x.group),...x,selected,done:x.done.filter((v:string)=>selected.includes(v))});records.current[x.group]=r;setS(r);setRole(r.role??-1);}}}catch{setStorageIssue(true)}setReady(true)},[]);
 const sendProgress=()=>{const payload=latestPayload.current;if(!payload)return;writeQueue.current=writeQueue.current.catch(()=>{}).then(async()=>{try{const response=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw Error('save');setSyncError(false)}catch{setSyncError(true)}})};
 useEffect(()=>{if(!ready)return;if(s.group)records.current[s.group]=s;try{localStorage.setItem('maeum-group-records',JSON.stringify(records.current));if(s.group)localStorage.setItem(key,JSON.stringify(s));}catch{setStorageIssue(true)}if(!s.group)return;latestPayload.current={device:device.current,group:s.group,record:s,revision:Date.now()};const timer=setTimeout(sendProgress,300);return()=>clearTimeout(timer)},[s,ready]);
 useEffect(()=>{if(!ready)return;const timer=setInterval(sendProgress,10000);const retry=()=>sendProgress();window.addEventListener('online',retry);return()=>{clearInterval(timer);window.removeEventListener('online',retry)}},[ready]);
 useEffect(()=>{if(!dashboard)return;const refresh=()=>fetch('/api/progress').then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>{setRows((x as {rows:any[]}).rows);setSyncError(false)}).catch(()=>setSyncError(true));refresh();const t=setInterval(refresh,4000);return()=>clearInterval(t)},[dashboard]);
 const enter=(g:number)=>{const r=normalizeFlow(records.current[g]||empty(g));setS(r);setRole(r.role??-1);setSettings(false);setChange(false)};
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),2500);return()=>clearTimeout(t)}},[notice]);
 const go=(screen:string)=>setS(p=>moveTo(p,screen)); const choose=(v:string)=>{if(s.screen==='extra'){setS(p=>({...p,extra:p.extra===v?null:v}));return;}if(s.selected.includes(v))setS(p=>({...p,selected:p.selected.filter(x=>x!==v)}));else if(s.selected.length<2)setS(p=>({...p,selected:[...p.selected,v]}));else setNotice('먼저 두 개를 표현해요.');};
 const finishGem=(v:string)=>setS(p=>toggleDone(p,v));
 const all=s.selected.length>=2&&s.selected.every(v=>s.done.includes(v));
 const gem=(v:string,i:number,on:boolean,click?:()=>void)=> <button key={v} className={'gem gem'+i+(on?' picked':'')} style={{'--gem-color':gemColors[v][0],'--gem-ink':gemColors[v][1]} as CSSProperties} aria-label={v} aria-pressed={on} onClick={click}><span className="facet"/><span className="gem-name">{v}</span>{on&&<span className="check">✓</span>}</button>;
 if(!ready)return <main className="app"><h1>💎 우리 모둠 마음보석</h1></main>;
 return <main className={'app group'+s.group}>
 <header><span className="brand">진주반 · 마음보석</span>{s.group>0&&<span className="group-label">{symbol(s.group)} {label(s.group)}</span>}<button className="home-button" aria-label="홈" onClick={()=>setHomeConfirm(true)}>🏠</button><button className="settings" aria-label="교사용 설정 길게 누르기" title="2초 동안 눌러요" onPointerDown={()=>{hold.current=setTimeout(()=>setSettings(true),1800)}} onPointerUp={()=>{if(hold.current)clearTimeout(hold.current)}} onPointerLeave={()=>{if(hold.current)clearTimeout(hold.current)}} onKeyDown={e=>{if(e.key==='Enter')setSettings(true)}}>⚙️</button></header>
 {!s.group?<section className="setup"><span className="eyebrow">진주반 · 우리 모둠</span><h1>우리 모둠을 정해요</h1><div className="group-grid">{hearts.map((h,i)=><button key={i} className={'group-choice group'+(i+1)} onClick={()=>enter(i+1)}>{symbol(i+1)} {label(i+1)}</button>)}</div></section>:<>
 {s.screen==='select'&&<section><h1>{symbol(s.group)} {label(s.group)} 마음보석 <span className="title-spark" aria-hidden="true">✦</span></h1><div className="picture-guide">{picture(1)}<span>친구들과 이야기해요</span>{picture(2)}<span>2개를 골라요</span></div><div className="gems four">{groups[s.group-1].map((v,i)=>gem(v,i,s.selected.includes(v),()=>choose(v)))}</div><footer><span className="short-reminder">친구들의 생각도 들어보았나요?</span><button className="primary" disabled={s.selected.length!==2} onClick={()=>go('confirm')}>{picture(4,"button-picture")} 선택했어요!</button></footer></section>}
 {s.screen==='confirm'&&<section><h1>✨ 우리가 고른 마음보석 ✨</h1><div className="gems two">{s.selected.map((v,i)=>gem(v,i,true,()=>go('select')))}</div><footer><button className="secondary" onClick={()=>go('select')}>{picture(2,"button-picture")} 다시 골라요</button><button className="primary" onClick={()=>go('roles')}>{picture(7,"button-picture")} 우리 역할 보기</button></footer></section>}
 {s.screen==='roles'&&<section><h1>👫 우리 모둠 역할</h1><div className="roles">{roles.map((r,i)=><button key={r[1]} className={'role '+(role===i?'active':'')} onClick={()=>{const next=role===i?-1:i;setRole(next);setS(p=>({...p,role:next}))}} aria-expanded={role===i}>{picture(rolePictures[i],"role-picture")}{r[1]}</button>)}</div><p className="role-description">{role>=0?roles[role][2]:'역할을 누르면 하는 일을 볼 수 있어요.'}</p><p className="everyone">{picture(7,"everyone-picture")}<span>생각하고 표현하기는<br/>우리 모두 함께해요!</span></p><footer><button className="secondary" onClick={()=>go('confirm')}>{picture(2,"button-picture")} 고른 보석 보기</button><button className="primary" onClick={()=>go('activity')}>{picture(3,"button-picture")} 마음보석을 표현해요</button></footer></section>}
 {(s.screen==='activity'||s.screen==='finish')&&<section><h1>{s.screen==='finish'?'✨ 우리가 표현한 마음보석':'💎 우리가 고른 마음보석'}</h1><div className="picture-guide">{picture(3)}<span>사진을 찍어요</span>{picture(4)}<span>다 찍으면 눌러요</span></div><div className={'activities count'+s.selected.length}>{s.selected.map((v,i)=><div className="activity" key={v}>{gem(v,i,s.done.includes(v),()=>finishGem(v))}<button className={'done '+(s.done.includes(v)?'completed':'')} onClick={()=>finishGem(v)}>{picture(4,'button-picture')}{s.done.includes(v)?'✓ 이 마음보석 다 했어요':'이 마음보석 다 했어요 ✓'}</button></div>)}</div><p className="completion">{all?(s.selected.length===2?'💎 두 마음보석을 모두 표현했어요!':s.selected.length===4?'💎 네 마음보석을 모두 표현했어요!':'💎 세 마음보석을 모두 표현했어요!'):'친구들과 함께 생각하고 표현해요.'}</p><footer><button className="secondary" onClick={()=>go('roles')}>{picture(7,"button-picture")} 우리 역할 보기</button>{all&&s.uploaded&&s.screen!=='finish'&&<div className="finish-actions">{s.selected.length<4&&<button className="primary" onClick={()=>go('extra')}>{picture(2,"button-picture")} 하나 더 표현할까요?</button>}<button className="secondary" onClick={()=>go('finish')}>{picture(4,"button-picture")} 여기까지 할래요</button></div>}{s.screen==='finish'&&<>{s.selected.length<4&&<button className="primary" onClick={()=>go('extra')}>{picture(2,'button-picture')} 하나 더 표현할까요?</button>}<button className="primary" onClick={()=>go('activity')}>{picture(3,"button-picture")} 활동으로 돌아가요</button></>}</footer></section>}
 {s.screen==='extra'&&<section><h1>⭐ 시간이 남았어요.</h1><div className="picture-guide">{picture(1)}<span>함께 이야기해요</span>{picture(2)}<span>하나 더 골라요</span></div><div className="gems two">{groups[s.group-1].filter(v=>!s.selected.includes(v)).map((v,i)=>gem(v,i,s.extra===v,()=>choose(v)))}</div><footer><button className="secondary" onClick={()=>go('activity')}>↶ 돌아갈래요</button><button className="primary" disabled={!s.extra} onClick={()=>setS(p=>({...p,selected:[...p.selected,p.extra!],extra:null,screen:'activity',uploaded:false,canva:false}))}>{picture(4,"button-picture")} 선택했어요!</button></footer></section>}

 {s.screen==='oneDone'&&<section><h1>하나 완성! ✨</h1><div className="picture-guide">{picture(3)}<span>이제 이 마음보석을 표현해요</span></div><div className="gems two">{s.selected.map((v,i)=>gem(v,i,s.done.includes(v),s.done.includes(v)?()=>finishGem(v):()=>go('activity')))}</div><footer><button className="primary" onClick={()=>go('activity')}>{picture(3,'button-picture')} 이어서 표현해요</button></footer></section>}
 {s.screen==='captured'&&all&&<section><h1>{s.selected.length===2?'두 마음보석을 모두 표현했어요! ✨✨':'고른 마음보석을 모두 표현했어요! ✨'}</h1><div className="gems two">{s.selected.map((v,i)=>gem(v,i,true,()=>finishGem(v)))}</div><footer><button className="primary" onClick={()=>go('return')}>{picture(5,'button-picture')} 모둠 자리로 돌아가요</button></footer></section>}
 {s.screen==='photos'&&all&&<section className="return-screen"><h1>우리 사진을 함께 확인해요</h1>{picture(6,'big-picture')}<div className="photo-pair" role="img" aria-label="찍은 마음보석 사진을 함께 확인하는 그림">{s.selected.map(v=><span key={v}>▧ {v} 사진 ✓</span>)}</div><footer><button className="primary" onClick={()=>go('upload')}>{picture(8,'button-picture')} 사진을 확인했어요</button></footer></section>}
 {s.screen==='return'&&all&&<section className="return-screen"><h1>모둠 자리로 돌아가요</h1>{picture(5,'big-picture')}<p className="question">친구들 모두 자리에 앉아요</p><footer><button className="primary gather-button" onClick={()=>go('photos')}>{picture(5,'gather-picture')} 모였어요!</button></footer></section>}
 {s.screen==='upload'&&all&&<section className="photo-screen"><h1>우리 사진을 함께 올려요</h1>{picture(6,'big-picture')}<div className="color-upload" style={{'--upload-color':colors[s.group-1],'--upload-ink':s.group===2?'#8a6508':colors[s.group-1]} as CSSProperties}><div className="upload-illustration" role="img" aria-label={colorNames[s.group-1]+' 사진칸에 사진을 넣는 그림'}>{picture(8,'upload-child')}<span className="upload-arrow">➜</span><span className="photo-slot">{picture(6,'slot-photo')}<span>사진</span></span></div><p>{symbol(s.group)} {s.group===5?'참관 선생님':label(s.group)}<br/><strong>{colorNames[s.group-1]} 칸에 {s.group===5?'사진':'우리 사진'}을 올려요!</strong></p></div><footer className="upload-footer"><a className="primary canva-button" href={canvaLink} target="_self" onClick={()=>{const r={...s,canva:true};latestPayload.current={device:device.current,group:s.group,record:r,revision:Date.now()};setS(r);try{localStorage.setItem(key,JSON.stringify(r));records.current[s.group]=r;localStorage.setItem('maeum-group-records',JSON.stringify(records.current))}catch{}navigator.sendBeacon('/api/progress',new Blob([JSON.stringify({device:device.current,group:s.group,record:r,revision:Date.now()})],{type:'application/json'}))}}><img className="canva-logo" src="/canva-logo.svg" alt="Canva 공식 로고"/>{picture(8,'button-picture')}<span>우리 사진 올리기</span></a><button className="secondary" onClick={()=>setS(p=>({...p,uploaded:true,canva:false,screen:'finish'}))}>{picture(4,'button-picture')} 사진 올렸어요</button></footer><p className="canva-back">◀ 사진을 올린 뒤 ‘뒤로’ 눌러 돌아와요</p></section>}
 </>}

 {homeConfirm&&<div className="overlay"><div className="dialog home-dialog" role="dialog" aria-modal="true" aria-label="처음으로 갈까요?"><div className="home-drawing">🏠</div><h2>처음으로 갈까요?</h2><p>고른 보석은 그대로 있어요</p><div className="home-actions"><button className="secondary" onClick={()=>setHomeConfirm(false)}>{picture(3,'button-picture')} 계속 할래요</button><button className="primary" onClick={()=>{setS(empty());setHomeConfirm(false);setSettings(false);setDashboard(false)}}>{picture(5,'button-picture')} 처음으로</button></div></div></div>}
 {dashboard&&<div className="overlay"><div className="dialog progress-dialog" role="dialog" aria-modal="true" aria-label="전체 진행상황"><h2>전체 진행상황</h2><h3>진주반 친구들</h3><div className="progress-grid">{[1,2,3,4].map(g=>{const r=rows.find(x=>x.group_id===g);return <article key={g} className={'progress-card group'+g}>{symbol(g)}<strong>{label(g)}</strong><p>{r?r.stage:syncError?'연결 확인 필요':'아직 시작 전'}</p><small>{r?JSON.parse(r.record_json).selected.join(' · '):'—'}</small>{rows.filter(x=>x.group_id===g).length>1&&rows.filter(x=>x.group_id===g).map((x,i)=><small key={x.device_id}>태블릿 {i+1} · {x.stage}</small>)}</article>})}</div><h3>참관 선생님</h3><div className="observer-progress"><span className="teacher-art">👩🏻‍🏫</span><strong>🟣 참관교사용</strong>{rows.filter(x=>x.group_id===5).length?rows.filter(x=>x.group_id===5).map((r,i)=><p key={r.device_id}>체험 {i+1} · {r.stage}<br/><small>{JSON.parse(r.record_json).selected.join(' · ')}</small></p>):<p>{syncError?'연결 확인 필요':'아직 시작 전'}</p>}</div><p className="dashboard-note">{syncError?'연결을 확인해 주세요. 저장된 마지막 상황이에요.':'여러 태블릿의 진행상황 · 4초마다 확인'}</p><button className="primary" onClick={()=>setDashboard(false)}>닫기</button></div></div>}
 {notice&&<div className="toast" role="status">{notice}</div>}
 {storageIssue&&<div className="storage-warning" role="alert">기록을 저장하기 어려워요. 선생님께 알려주세요.</div>}
 {settings&&<div className="overlay"><div className="dialog" role="dialog" aria-modal="true" aria-label="교사용 설정"><h2>⚙️ 교사용 설정</h2><p className="sync-status">{syncError?'공유 연결을 확인해 주세요. 이 태블릿에는 저장되어 있어요.':'진행상황 공유 연결됨'}</p><p>현재 모둠: {s.group?label(s.group):'설정 전'}</p><div className="records">{s.selected.length?s.selected.map(v=><p key={v}>{s.done.includes(v)?'✓':'◇'} {v} · {s.done.includes(v)?'촬영 완료':'표현 중'}</p>):<p>선택한 마음보석 없음</p>}</div>{change?<><p>모둠을 다시 고르면 이어서 할 수 있어요</p><div className="settings-groups">{hearts.map((h,i)=><button key={i} onClick={()=>{enter(i+1)}}>{symbol(i+1)} {label(i+1)}</button>)}</div><button className="secondary" onClick={()=>setChange(false)}>취소</button></>:<><button className="secondary" onClick={()=>setChange(true)}>모둠 변경</button><button className="secondary" onClick={()=>{setSettings(false);setDashboard(true)}}>전체 진행상황</button></>}{reset?<div className="reset-confirm"><h3>처음부터 다시 할까요?</h3><button className="secondary" onClick={()=>setReset(false)}>취소</button><button className="primary" onClick={()=>{records.current[s.group]=empty(s.group);setS(empty(s.group));setRole(-1);setReset(false);setSettings(false)}}>처음부터</button></div>:<button className="secondary" onClick={()=>setReset(true)}>이 태블릿 기록 초기화</button>}<button className="primary" onClick={()=>{setSettings(false);setChange(false);setReset(false)}}>닫기</button></div></div>}
 </main>;
}
