'use client';
import {normalizeFlow,toggleDone,moveTo,backTo,stageOf} from '../server/activity-flow.mjs';
import {useEffect,useRef,useState, type CSSProperties} from 'react';
const groups=[['협동','책임','경청','감사'],['배려','질서','공감','용기'],['경청','성실','협동','예의'],['공감','끈기','배려','자주'],['존중','경청','공감','협동']];
const gemColors:Record<string,[string,string]>={존중:['#35b8ad','#165b62'],협동:['#7961d2','#38277f'],책임:['#a3a3aa','#454650'],경청:['#62bfdf','#14566d'],감사:['#ef555b','#932a30'],배려:['#c97872','#703b39'],질서:['#d263a7','#7a285c'],공감:['#d5a64d','#795722'],용기:['#61c894','#226849'],성실:['#b3d663','#5b7425'],예의:['#e5985e','#86452b'],끈기:['#646dd0','#292f7d'],자주:['#dfc351','#7a661b']};
const groupNames=['다람쥐','낙엽','잠자리','바람','참관교사용'];
const symbol=(n:number)=> n===5?<span className="teacher-art" aria-hidden="true">👩🏻‍🏫</span>:<span className={'group-art art'+n} aria-hidden="true"/>;
const hearts=['❤️','💛','💚','💙','🟣'];
const roles=[['💬','진행자','친구들의 생각을 들어요.'],['🎬','감독','우리 생각이 잘 보이도록 장면을 만들어요.'],['📷','촬영자','사진을 찍어요.'],['📤','올림이','사진을 캔바에 올려요.'],['💎','완성이','우리 사진을 미덕송에 넣어요.']];
const pictureLabels=['친구들이 함께 이야기하는 그림','친구들이 보석을 함께 고르는 그림','태블릿으로 친구들을 촬영하는 그림','두 손을 들고 완료를 표시하는 유아 그림','다섯 친구가 모둠 책상 앞 의자에 앉은 그림','다섯 친구가 태블릿 사진을 함께 확인하는 그림','친구들이 함께 촬영 장면을 만드는 그림','사진을 올리는 그림','사진을 미덕송 화면에 넣는 그림'];
const picture=(n:number,cls='')=><span className={'action-picture picture'+n+' '+cls} role="img" aria-label={pictureLabels[n-1]}/>;
const rolePictures=[1,7,3,8,9];
const roleNumbers=['①','②','③','④','⑤'];
const operatorFor=(screen:string)=>({leader:[1,'진행자를 확인해요'],select:[1,'마음보석을 골라요'],confirm:[1,'고른 보석을 확인해요'],roles:[2,'역할을 확인해요'],discussion:[2,'준비되면 눌러요'],activity:[3,'사진을 찍어요'],oneDone:[3,'사진을 찍어요'],captured:[3,'촬영을 마무리해요'],return:[3,'모이면 눌러요'],photos:[4,'우리 사진을 확인해요'],upload:[4,'사진을 올려요']}[screen]||[1,'눌러주세요']) as [number,string];
const canvaLink='https://canva.link/lg44g9coxwzxamt';
const appIcon=(name:'camera'|'gallery'|'canva',cls='')=><img className={'real-app-icon '+cls} src={'/app-icons/'+name+'.png'} alt={{camera:'카메라 앱 아이콘',gallery:'갤러리 앱 아이콘',canva:'Canva 앱 아이콘'}[name]}/>;
type RecordState={group:number;selected:string[];done:string[];screen:string;extra:string|null;pending?:string|null;role?:number;canva?:boolean;uploaded?:boolean;leaderConfirmed?:boolean;reviewing?:boolean};
const empty=(group=0):RecordState=>({group,selected:[],done:[],screen:'select',extra:null});
const key='diamond-maeum-v1';
const colors=['#e4424c','#e8bc23','#2fa56b','#3889db','#975aca'];
const colorNames=['빨간색','노란색','초록색','파란색','보라색'];
const label=(g:number)=>g===5?'참관교사용':groupNames[g-1]+' 모둠';
const stage=stageOf;
const progressSteps=['준비','사진1','사진2','사진확인','Canva'];
const boardProgress=(row:any)=>{
 let r:Partial<RecordState>={};try{r=row?JSON.parse(row.record_json):{}}catch{}
 const count=Array.isArray(r.done)&&Array.isArray(r.selected)?r.selected.filter(v=>r.done!.includes(v)).length:0;
 const launched=['activity','oneDone','captured','return','photos','upload'].includes(r.screen||'')||count>0||r.canva===true;
 const checked=r.screen==='upload'||r.canva===true;
 const done=r.reviewing&&r.screen==='activity'?[true,false,false,false,false]:r.reviewing&&r.screen==='oneDone'?[true,true,false,false,false]:['leader','select','confirm','roles','discussion'].includes(r.screen||'')?[false,false,false,false,false]:[launched,count>=1,count>=2,checked,r.canva===true];
 const current=row?done.findIndex(v=>!v):-1;
 return {done,current};
};
const boardRow=(g:number,row:any)=>{const progress=boardProgress(row);return <article key={g} data-group={g} className={'board-row group'+g}><strong className="board-group">{symbol(g)}{label(g)}</strong>{progressSteps.map((name,i)=>{const state=progress.done[i]?'done':progress.current===i?'current':'pending';return <span key={name} className={'board-step '+state} data-step={name} data-state={state} aria-label={name+' '+({done:'완료',current:'진행 중',pending:'아직'}[state])}><span>{name}</span><b aria-hidden="true">{progress.done[i]?'✓':'○'}</b></span>})}</article>};
export default function Home(){
 const [s,setS]=useState<RecordState>(empty()),[ready,setReady]=useState(false),[role,setRole]=useState(-1),[notice,setNotice]=useState(''),[storageIssue,setStorageIssue]=useState(false);const [homeConfirm,setHomeConfirm]=useState(false),[dashboard,setDashboard]=useState(false),[rows,setRows]=useState<any[]>([]),[syncError,setSyncError]=useState(false),[resetConfirm,setResetConfirm]=useState(false),[resetBusy,setResetBusy]=useState(false);const resetVersion=useRef('0');const records=useRef<Record<number,RecordState>>({});const device=useRef('');const latestPayload=useRef<any>(null);const writeQueue=useRef(Promise.resolve());
 useEffect(()=>{try{resetVersion.current=localStorage.getItem('maeum-reset-version')||'0';device.current=localStorage.getItem('maeum-device')||(typeof crypto.randomUUID==='function'?crypto.randomUUID():'tablet-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));localStorage.setItem('maeum-device',device.current);records.current=JSON.parse(localStorage.getItem('maeum-group-records')||'{}');const raw=localStorage.getItem(key);if(raw){const x=JSON.parse(raw);if(Number.isInteger(x.group)&&x.group>=1&&x.group<=5&&Array.isArray(x.selected)&&Array.isArray(x.done)){const selected=[...new Set<string>(x.selected.filter((v:string)=>groups[x.group-1].includes(v)))];const r=normalizeFlow({...empty(x.group),...x,selected,done:x.done.filter((v:string)=>selected.includes(v))});records.current[x.group]=r;setS(r);setRole(r.role??-1);}}}catch{setStorageIssue(true)}setReady(true)},[]);
 const applyReset=(version:string)=>{version=String(version??'0');if(version===resetVersion.current||Number(version.split('-')[0])<Number(resetVersion.current.split('-')[0]))return false;resetVersion.current=version;records.current={};latestPayload.current=null;setS(empty());setRole(-1);setHomeConfirm(false);setRows([]);try{localStorage.removeItem(key);localStorage.setItem('maeum-group-records','{}');localStorage.setItem('maeum-reset-version',version)}catch{setStorageIssue(true)}return true};
 const checkReset=async()=>{const response=await fetch('/api/progress',{cache:'no-store'});if(!response.ok)throw Error('reset-check');const x=await response.json();return applyReset(String(x.resetVersion??'0'))};
 useEffect(()=>{if(ready)checkReset().catch(()=>setSyncError(true))},[ready]);
 const sendProgress=()=>{const payload=latestPayload.current;writeQueue.current=writeQueue.current.catch(()=>{}).then(async()=>{try{if(await checkReset())return;if(!payload||String(payload.resetVersion)!==resetVersion.current)return;const response=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(response.status===409){const x=await response.json();applyReset(x.resetVersion);return}if(!response.ok)throw Error('save');setSyncError(false)}catch{setSyncError(true)}})};
 useEffect(()=>{if(!ready)return;if(s.group)records.current[s.group]=s;try{localStorage.setItem('maeum-group-records',JSON.stringify(records.current));if(s.group)localStorage.setItem(key,JSON.stringify(s));}catch{setStorageIssue(true)}if(!s.group)return;latestPayload.current={device:device.current,group:s.group,record:s,resetVersion:resetVersion.current,revision:Date.now()};const timer=setTimeout(sendProgress,300);return()=>clearTimeout(timer)},[s,ready]);
 useEffect(()=>{if(!ready)return;const timer=setInterval(sendProgress,10000);const retry=()=>sendProgress();window.addEventListener('online',retry);return()=>{clearInterval(timer);window.removeEventListener('online',retry)}},[ready]);
 const refreshProgress=async()=>{try{const response=await fetch('/api/progress',{cache:'no-store'});if(!response.ok)throw Error();const x=await response.json();const incomingVersion=String(x.resetVersion??'0');if(Number(incomingVersion.split('-')[0])<Number(resetVersion.current.split('-')[0]))return;applyReset(incomingVersion);setRows(x.rows);setSyncError(false)}catch{setSyncError(true);setRows(previous=>{const local=Object.values(records.current).map(record=>({device_id:device.current,group_id:record.group,record_json:JSON.stringify(record),stage:stage(record),local:true}));return [...previous.filter(row=>!local.some(x=>x.device_id===row.device_id&&x.group_id===row.group_id)),...local]})}};
 useEffect(()=>{if(!dashboard)return;refreshProgress();const t=setInterval(refreshProgress,4000);return()=>clearInterval(t)},[dashboard]);
 const resetAll=async()=>{setResetBusy(true);try{const response=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset',resetVersion:resetVersion.current})});const x=await response.json();if(response.status===409){applyReset(x.resetVersion);setNotice('다시 확인해 주세요.');return}if(!response.ok)throw Error();applyReset(x.resetVersion);setResetConfirm(false);setNotice('모든 진행상황을 초기화했어요 ✓')}catch{setNotice('연결을 확인해 주세요. 초기화하지 못했어요.')}finally{setResetBusy(false)}};
 const enter=(g:number)=>{const r=normalizeFlow(records.current[g]||{...empty(g),screen:'leader',leaderConfirmed:false});setS(r);setRole(r.role??-1)};
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),2500);return()=>clearTimeout(t)}},[notice]);
 const go=(screen:string)=>setS(p=>moveTo(p,screen)); const choose=(v:string)=>{if(s.screen==='extra'){setS(p=>({...p,extra:p.extra===v?null:v}));return;}if(s.selected.includes(v))setS(p=>({...p,selected:p.selected.filter(x=>x!==v),done:p.done.filter(x=>x!==v),canva:false}));else if(s.selected.length<2)setS(p=>({...p,selected:[...p.selected,v]}));else setNotice('먼저 두 개를 표현해요.');};
 const finishGem=(v:string)=>setS(p=>toggleDone(p,v));
 const back=()=>{const previous:Record<string,string>={select:'leader',confirm:'select',roles:'select',discussion:'roles',activity:'discussion',oneDone:'activity',captured:'oneDone',return:'oneDone',photos:'return',upload:'photos'};if(previous[s.screen])setS(p=>backTo(p,previous[p.screen]))};
 const [operator,operatorAction]=operatorFor(s.screen);
 const all=s.selected.length>=2&&s.selected.every(v=>s.done.includes(v));
 const gem=(v:string,i:number,on:boolean,click?:()=>void)=> <button key={v} className={'gem gem'+i+(on?' picked':'')} style={{'--gem-color':gemColors[v][0],'--gem-ink':gemColors[v][1]} as CSSProperties} aria-label={v} aria-pressed={on} onClick={click}><span className="facet"/><span className="gem-name">{v}</span>{on&&<span className="check">✓</span>}</button>;
 if(!ready)return <main className="app"><h1>💎 우리 모둠 마음보석</h1></main>;
 return <main className={'app group'+s.group+(s.group&&!(s.screen==='leader'&&!s.leaderConfirmed)?' has-operator':'')}>
 <header><span className="brand">다이아몬드반 · 마음보석</span>{s.group>0&&<span className="group-label">{symbol(s.group)} {label(s.group)}</span>}<button className="home-button" aria-label="홈" onClick={()=>setHomeConfirm(true)}>🏠</button><button className="progress-button" onClick={()=>setDashboard(true)}>📊 진행상황 보기</button></header>
 {s.group>0&&!(s.screen==='leader'&&!s.leaderConfirmed)&&<aside className="operator-rail">{s.screen!=='leader'?<button className="back-button" onClick={back}>← 뒤로</button>:<span className="operator-back-space" aria-hidden="true"/>}<div className="operator-badge" role="note" aria-label={'태블릿 조작 담당 '+roleNumbers[operator-1]+' '+roles[operator-1][1]}><b className="operator-number">{roleNumbers[operator-1]}</b><strong>{roles[operator-1][1]}</strong>{picture(rolePictures[operator-1],'operator-picture')}<span>{operatorAction}</span></div></aside>}
 {!s.group?<section className="setup"><span className="eyebrow">다이아몬드반 · 우리 모둠</span><h1>우리 모둠을 정해요</h1><div className="group-grid">{hearts.map((h,i)=><button key={i} className={'group-choice group'+(i+1)} onClick={()=>enter(i+1)}>{symbol(i+1)} {label(i+1)}</button>)}</div></section>:<>
 {s.screen==='leader'&&<section className="leader-screen"><h1>🌟 오늘의 진행자는 누구일까요?</h1>{!s.leaderConfirmed?<div className="leader-reveal"><button className="primary leader-discover" onClick={()=>setS(p=>({...p,leaderConfirmed:true}))}>🌟 오늘의 진행자 확인하기</button></div>:<><div className="leader-reveal"><div className="role leader-card leader-picked">{picture(1,'leader-picture')}<span className="role-name">🌟 ① 진행자</span><span className="leader-check">✓</span></div><p className="question">친구들의 생각을 잘 들어주세요.</p></div><footer><button className="primary" onClick={()=>go('select')}>{picture(4,'button-picture')} ① 진행자 준비됐어요!</button></footer></>}</section>}
 {s.screen==='select'&&<section><h1>{symbol(s.group)} {label(s.group)} 마음보석 <span className="title-spark" aria-hidden="true">✦</span></h1><div className="picture-guide">{picture(1)}<span>친구들과 이야기해요</span>{picture(2)}<span>2개를 골라요</span></div><div className="gems four">{groups[s.group-1].map((v,i)=>gem(v,i,s.selected.includes(v),()=>choose(v)))}</div><footer><span className="short-reminder">친구들의 생각도 들어보았나요?</span><button className="primary" disabled={s.selected.length!==2} onClick={()=>go('confirm')}>{picture(4,"button-picture")} 선택했어요!</button></footer></section>}
 {s.screen==='confirm'&&<section><h1>✨ 우리가 고른 마음보석 ✨</h1><div className="gems two">{s.selected.map((v,i)=>gem(v,i,true,()=>go('select')))}</div><footer><button className="secondary" onClick={()=>go('select')}>{picture(2,"button-picture")} 다시 골라요</button><button className="primary" onClick={()=>go('roles')}>{picture(7,"button-picture")} 우리 역할 보기</button></footer></section>}
 {s.screen==='roles'&&<section><h1>👫 우리 모둠 역할</h1><div className="roles">{roles.map((r,i)=><button key={r[1]} className={'role '+(role===i?'active':'')} onClick={()=>{const next=role===i?-1:i;setRole(next);setS(p=>({...p,role:next}))}} aria-expanded={role===i}>{i===2||i===3?<span className="role-visuals">{picture(rolePictures[i],"role-picture")}{appIcon(i===2?'camera':'canva','role-app-icon')}</span>:picture(rolePictures[i],"role-picture")}<span className="role-name">{roleNumbers[i]} {r[1]}</span></button>)}</div><p className="role-description">{role>=0?roles[role][2]:roles[0][2]}</p><p className="everyone">{picture(7,"everyone-picture")}<span>생각하고 표현하기는<br/>우리 모두 함께해요!</span></p><footer><button className="secondary" onClick={()=>go('confirm')}>{picture(2,"button-picture")} 고른 보석 보기</button><button className="primary" onClick={()=>go(s.done.length&&!s.reviewing?'activity':'discussion')}>{picture(s.done.length?3:1,"button-picture")} {s.done.length&&!s.reviewing?'이어서 표현해요':'두 마음보석 이야기해요'}</button></footer></section>}
 {s.screen==='discussion'&&<section className="discussion-screen"><h1>두 마음보석을 어떻게 표현할지 이야기해요</h1><div className="discussion-gems">{s.selected.map((v,i)=><div className="discussion-card" key={v}>{gem(v,i,false)}<div className="discussion-question"><svg className="place-picture" viewBox="0 0 80 80" role="img" aria-label="사진 찍을 곳을 생각하는 위치 그림"><path d="M40 5C21 5 12 18 12 32c0 19 28 42 28 42s28-23 28-42C68 18 59 5 40 5Z" fill="#f2b986" stroke="#a05d45" strokeWidth="3"/><circle cx="40" cy="31" r="13" fill="#fffaf0"/><path d="M34 31h12M40 25v12" stroke="#a05d45" strokeWidth="3" strokeLinecap="round"/></svg><span>어디에서 찍을까?</span></div><div className="discussion-question">{picture(7,'discussion-picture')}<span>어떤 모습으로 표현할까?</span></div></div>)}</div><div className="discussion-reminder">{picture(1,'discussion-picture')}<span>친구들의 생각을 모두 들었나요?<br/>두 마음보석 모두 정했으면 출발해요!</span></div><footer className="guided-footer"><button className="primary" onClick={()=>go('activity')}>{picture(3,'button-picture')} 의논했어요! 촬영하러 출발 🚶</button></footer></section>}
 {s.screen==='activity'&&<section><h1>💎 우리가 고른 마음보석</h1><div className="picture-guide">{appIcon('camera')}{picture(3)}<span>사진을 찍어요</span>{picture(4)}<span>다 찍으면 눌러요</span></div><div className={'activities count'+s.selected.length}>{s.selected.map((v,i)=><div className="activity" key={v}>{gem(v,i,s.done.includes(v),()=>finishGem(v))}<button className={'done '+(s.done.includes(v)?'completed':'')} onClick={()=>finishGem(v)}>{picture(4,'button-picture')}{s.done.includes(v)?'✓ 이 마음보석 다 했어요':'이 마음보석 다 했어요 ✓'}</button></div>)}</div><p className="completion">친구들과 함께 생각하고 표현해요.</p><footer><button className="secondary" onClick={()=>go('roles')}>{picture(7,'button-picture')} 우리 역할 보기</button>{all&&<button className="primary" onClick={()=>go('captured')}>{picture(4,'button-picture')} 모두 표현했어요</button>}</footer></section>}
 {s.screen==='oneDone'&&<section><h1>{s.reviewing&&all?'두 번째 마음보석을 확인해요':'하나 완성! ✨'}</h1><div className="picture-guide">{appIcon('camera')}{picture(3)}<div className="second-camera-guide"><span>이제 이 마음보석을 표현해요</span><span>사진을 찍어요</span></div></div><div className="gems two">{s.selected.map((v,i)=>gem(v,i,s.done.includes(v),s.done.includes(v)?()=>finishGem(v):()=>go('activity')))}</div><footer><button className="primary" onClick={()=>{const next=s.selected.find(v=>!s.done.includes(v));if(next)finishGem(next);else go('captured')}}>{picture(4,'button-picture')} 이 마음보석 다 했어요 ✓</button></footer></section>}
 {s.screen==='captured'&&all&&<section><h1>{s.selected.length===2?'두 마음보석을 모두 표현했어요! ✨✨':'고른 마음보석을 모두 표현했어요! ✨'}</h1><div className="gems two">{s.selected.map((v,i)=>gem(v,i,true,()=>finishGem(v)))}</div><footer><button className="primary" onClick={()=>go('return')}>{picture(5,'button-picture')} 모둠 자리로 돌아가요</button></footer></section>}
 {s.screen==='photos'&&all&&<section className="return-screen"><h1>우리 사진을 함께 확인해요</h1><div className="app-picture-pair">{appIcon('gallery','large-app-icon')}{picture(6,'big-picture')}</div><div className="gallery-role-guide"><span className="gallery-open-guide">갤러리를 열어요</span><p className="question">사진 앱에서 함께 보고 돌아와요</p><p className="photo-together">사진은 친구들과 함께 골라요</p></div><div className="photo-pair" role="img" aria-label="찍은 마음보석 사진을 함께 확인하는 그림">{s.selected.map(v=><span key={v}>▧ {v} 사진 ✓</span>)}</div><footer><button className="primary" onClick={()=>go('upload')}>{picture(8,'button-picture')} 사진을 확인했어요</button></footer></section>}
 {s.screen==='return'&&all&&<section className="return-screen"><h1>모둠 자리로 돌아가요</h1>{picture(5,'big-picture')}<p className="question">친구들 모두 자리에 앉아요</p><footer><button className="primary gather-button" onClick={()=>go('photos')}>{picture(5,'gather-picture')} 모였어요!</button></footer></section>}
 {s.screen==='upload'&&all&&<section className="photo-screen"><h1>우리 사진을 함께 올려요</h1>{picture(6,'big-picture')}<div className="color-upload" style={{'--upload-color':colors[s.group-1],'--upload-ink':s.group===2?'#8a6508':colors[s.group-1]} as CSSProperties}><div className="upload-illustration" role="img" aria-label={colorNames[s.group-1]+' 사진칸에 사진을 넣는 그림'}>{picture(8,'upload-child')}<span className="upload-arrow">➜</span><span className="photo-slot">{picture(6,'slot-photo')}<span>사진</span></span></div><p>{symbol(s.group)} {s.group===5?'참관 선생님':label(s.group)}<br/><strong>{colorNames[s.group-1]} 칸에 {s.group===5?'사진':'우리 사진'}을 올려요!</strong></p><p className="upload-finish-note">사진을 올리면 우리 모둠 활동 끝! 🎉</p></div><footer className="upload-footer guided-footer"><a className="primary canva-button" href={canvaLink} target="_self" onClick={()=>{const r={...s,canva:true};latestPayload.current={device:device.current,group:s.group,record:r,resetVersion:resetVersion.current,revision:Date.now()};setS(r);try{localStorage.setItem(key,JSON.stringify(r));records.current[s.group]=r;localStorage.setItem('maeum-group-records',JSON.stringify(records.current))}catch{}const payload=JSON.stringify(latestPayload.current);if(!navigator.sendBeacon('/api/progress',new Blob([payload],{type:'application/json'})))fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:payload,keepalive:true}).catch(()=>{})}}>{appIcon('canva','canva-app-icon')}{picture(8,'button-picture')}<span>우리 사진 올리기</span></a></footer></section>}
 </>}

 {homeConfirm&&<div className="overlay"><div className="dialog home-dialog" role="dialog" aria-modal="true" aria-label="처음으로 갈까요?"><div className="home-drawing">🏠</div><h2>처음으로 갈까요?</h2><p>고른 보석은 그대로 있어요</p><div className="home-actions"><button className="secondary" onClick={()=>setHomeConfirm(false)}>{picture(3,'button-picture')} 계속 할래요</button><button className="primary" onClick={()=>{setS(empty());setHomeConfirm(false);setDashboard(false)}}>{picture(5,'button-picture')} 처음으로</button></div></div></div>}
 {dashboard&&<div className="overlay"><div className="dialog progress-dialog whiteboard-dialog" role="dialog" aria-modal="true" aria-label="전체 진행상황"><h2>전체 진행상황</h2><h3>다이아몬드반 친구들</h3><div className="board-children">{[1,2,3,4].map(g=>boardRow(g,rows.find(x=>x.group_id===g)))}</div><div className="board-observer"><h3>참관 선생님</h3>{boardRow(5,rows.find(x=>x.group_id===5))}</div><p className="dashboard-note">{syncError?'연결 확인 필요 · 저장된 진행상황':'여러 태블릿의 진행상황 · 4초마다 확인'}</p><div className="progress-actions"><button className="secondary" onClick={()=>setResetConfirm(true)}>🔄 전체 진행상황 초기화</button><button className="secondary" onClick={refreshProgress}>↻ 새로고침</button><button className="primary" onClick={()=>setDashboard(false)}>← 돌아가기</button></div><div className={'teacher-canva-area'+([1,2,3,4].every(g=>boardProgress(rows.find(x=>x.group_id===g)).done[4])?' all-ready':'')}>{[1,2,3,4].every(g=>boardProgress(rows.find(x=>x.group_id===g)).done[4])&&<p className="all-groups-ready">✨ 모든 모둠의 활동이 끝났어요!</p>}<a className="primary teacher-canva-button" href={canvaLink} target="_blank" rel="noopener noreferrer">🎨 교사용 Canva 열기</a></div></div></div>}
 {resetConfirm&&<div className="overlay reset-overlay"><div className="dialog" role="dialog" aria-modal="true" aria-label="전체 진행상황 초기화 확인"><h2>모든 모둠과 참관교사용 진행상황을 처음으로 되돌릴까요?</h2><div className="home-actions"><button className="secondary" disabled={resetBusy} onClick={()=>setResetConfirm(false)}>취소</button><button className="primary" disabled={resetBusy} onClick={resetAll}>{resetBusy?'초기화 중…':'모두 초기화'}</button></div></div></div>}
 {notice&&<div className="toast" role="status">{notice}</div>}
 {storageIssue&&<div className="storage-warning" role="alert">기록을 저장하기 어려워요. 선생님께 알려주세요.</div>}

 </main>;
}
